# Pivot tables for heatmaps

## Load data

In [2]:
path = '../../data/EIA/fuel_type_data_california.parquet'

In [3]:
import pandas as pd
df = pd.read_parquet(path).set_index('period').sort_index()

df = df.loc['2024', ['type-name', 'fueltype', 'value']]
df.columns = ['technology', 'tech', 'energy']

df

                          technology tech  energy
period
2024-01-01 00:00:00-07:00       Wind  WND     243
2024-01-01 00:00:00-07:00      Hydro  WAT    3541
...                              ...  ...     ...
2024-12-31 23:00:00-07:00      Hydro  WAT    4125
2024-12-31 23:00:00-07:00       Wind  WND     476

[70224 rows x 3 columns]

## Calculate temporal properties

In [4]:
from modules import utils
df = utils.add_time_features(df)

df

ModuleNotFoundError: No module named 'modules'

In [5]:
df["year"] = df.index.year
df["month"]= df.index.month
df["day"]= df.index.day
df["hour"]= df.index.hour
df["weekday"]= df.index.weekday
df["weekend"]= df.index.dayofweek > 4

## Steps
### Aggregate data with pivot table

In [6]:
df.pivot_table?

Signature:
df.pivot_table(
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Level' = 'All',
    observed: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
values : list-like or scalar, optional
    Column or columns to aggregate.
index : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table index. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
columns : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table column. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
aggfunc : function, list of functions, dict, default "mean"
    If a list of functions is passed, the resulting pivot table will have
    hierarchical columns whose top level are the function names
    (inferred from the function objects themselves).
    If a dict is passed, the key is column to aggregate and the value is
    function or list of functions. If ``margin=True``, aggfunc will be
    used to calculate the partial aggregates.
fill_value : scalar, default None
    Value to replace missing values with (in the resulting pivot table,
    after aggregation).
margins : bool, default False
    If ``margins=True``, special ``All`` columns and rows
    will be added with partial group aggregates across the categories
    on the rows and columns.
dropna : bool, default True
    Do not include columns whose entries are all NaN. If True,
    rows with a NaN value in any column will be omitted before
    computing margins.
margins_name : str, default 'All'
    Name of the row / column that will contain the totals
    when margins is True.
observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.

    .. deprecated:: 2.2.0

        The default value of ``False`` is deprecated and will change to
        ``True`` in a future version of pandas.

sort : bool, default True
    Specifies if the result should be sorted.

    .. versionadded:: 1.3.0

Returns
-------
DataFrame
    An Excel style pivot table.

See Also
--------
DataFrame.pivot : Pivot without aggregation that can handle
    non-numeric data.
DataFrame.melt: Unpivot a DataFrame from wide to long format,
    optionally leaving identifiers set.
wide_to_long : Wide panel to long format. Less flexible but more
    user-friendly than melt.

Notes
-----
Reference :ref:`the user guide <reshaping.pivot>` for more examples.

Examples
--------
>>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
...                          "bar", "bar", "bar", "bar"],
...                    "B": ["one", "one", "one", "two", "two",
...                          "one", "one", "two", "two"],
...                    "C": ["small", "large", "large", "small",
...                          "small", "large", "small", "small",
...                          "large"],
...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
>>> df
     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

This first example aggregates values by taking the sum.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                        columns=['C'], aggfunc="sum")
>>> table
C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

We can also fill missing values using the `fill_value` parameter.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                        columns=['C'], aggfunc="sum", fill_value=0)
>>> table
C        large  small
A   B
bar one      4      5
    two      7      6
foo one      4      1
    two      0      6

The next example aggregates by taking the mean across multiple columns.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                        aggfunc={'D': "mean", 'E': "mean"})
>>> table
                D         E
A   C
bar large  5.500000  7.500000
    small  5.500000  8.500000
foo large  2.000000  4.500000
    small  2.333333  4.333333

We can also calculate multiple types of aggregations for any given
value column.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                        aggfunc={'D': "mean",
...                                 'E': ["min", "max", "mean"]})
>>> table
                  D   E
               mean max      mean  min
A   C
bar large  5.500000   9  7.500000    6
    small  5.500000   9  8.500000    8
foo large  2.000000   5  4.500000    4
    small  2.333333   6  4.333333    2
File:      /opt/venv/lib/python3.10/site-packages/pandas/core/frame.py
Type:      method

In [8]:
df[["tech", "technology"]].drop_duplicates().style

In [15]:
c_num = "energy"
c_cat_idx = "hour"
c_cat_col = "tech"

r = df.pivot_table(
    values=c_num,
    index=c_cat_idx,
    columns=c_cat_col,
    aggfunc='mean',
)

### Style background gradient to visualize heatmatrix

In [12]:
r.style.background_gradient?

Signature:
r.style.background_gradient(
    cmap: 'str | Colormap' = 'PuBu',
    low: 'float' = 0,
    high: 'float' = 0,
    axis: 'Axis | None' = 0,
    subset: 'Subset | None' = None,
    text_color_threshold: 'float' = 0.408,
    vmin: 'float | None' = None,
    vmax: 'float | None' = None,
    gmap: 'Sequence | None' = None,
) -> 'Styler'
Docstring:
Color the background in a gradient style.

The background color is determined according
to the data in each column, row or frame, or by a given
gradient map. Requires matplotlib.

Parameters
----------
cmap : str or colormap
    Matplotlib colormap.
low : float
    Compress the color range at the low end. This is a multiple of the data
    range to extend below the minimum; good values usually in [0, 1],
    defaults to 0.
high : float
    Compress the color range at the high end. This is a multiple of the data
    range to extend above the maximum; good values usually in [0, 1],
    defaults to 0.
axis : {0, 1, "index", "columns", None}, default 0
    Apply to each column (``axis=0`` or ``'index'``), to each row
    (``axis=1`` or ``'columns'``), or to the entire DataFrame at once
    with ``axis=None``.
subset : label, array-like, IndexSlice, optional
    A valid 2d input to `DataFrame.loc[<subset>]`, or, in the case of a 1d input
    or single key, to `DataFrame.loc[:, <subset>]` where the columns are
    prioritised, to limit ``data`` to *before* applying the function.
text_color_threshold : float or int

            Luminance threshold for determining text color in [0, 1]. Facilitates text

            visibility across varying background colors. All text is dark if 0, and

            light if 1, defaults to 0.408.
vmin : float, optional
    Minimum data value that corresponds to colormap minimum value.
    If not specified the minimum value of the data (or gmap) will be used.
vmax : float, optional
    Maximum data value that corresponds to colormap maximum value.
    If not specified the maximum value of the data (or gmap) will be used.
gmap : array-like, optional
    Gradient map for determining the background colors. If not supplied
    will use the underlying data from rows, columns or frame. If given as an
    ndarray or list-like must be an identical shape to the underlying data
    considering ``axis`` and ``subset``. If given as DataFrame or Series must
    have same index and column labels considering ``axis`` and ``subset``.
    If supplied, ``vmin`` and ``vmax`` should be given relative to this
    gradient map.

    .. versionadded:: 1.3.0

Returns
-------
Styler

See Also
--------
Styler.text_gradient: Color the text in a gradient style.

Notes
-----
When using ``low`` and ``high`` the range
of the gradient, given by the data if ``gmap`` is not given or by ``gmap``,
is extended at the low end effectively by
`map.min - low * map.range` and at the high end by
`map.max + high * map.range` before the colors are normalized and determined.

If combining with ``vmin`` and ``vmax`` the `map.min`, `map.max` and
`map.range` are replaced by values according to the values derived from
``vmin`` and ``vmax``.

This method will preselect numeric columns and ignore non-numeric columns
unless a ``gmap`` is supplied in which case no preselection occurs.

Examples
--------
>>> df = pd.DataFrame(columns=["City", "Temp (c)", "Rain (mm)", "Wind (m/s)"],
...                   data=[["Stockholm", 21.6, 5.0, 3.2],
...                         ["Oslo", 22.4, 13.3, 3.1],
...                         ["Copenhagen", 24.5, 0.0, 6.7]])

Shading the values column-wise, with ``axis=0``, preselecting numeric columns

>>> df.style.background_gradient(axis=0)  # doctest: +SKIP

.. figure:: ../../_static/style/bg_ax0.png

Shading all values collectively using ``axis=None``

>>> df.style.background_gradient(axis=None)  # doctest: +SKIP

.. figure:: ../../_static/style/bg_axNone.png

Compress the color map from the both ``low`` and ``high`` ends

>>> df.style.background_gradient(axis=None, low=0.75, high=1.0)  # doctest: +SKIP

.. figure:: ../../_static/style/bg_axNone_lowhigh.png

Manually setting ``vmin`` and ``vmax`` gradient thresholds

>>> df.style.background_gradient(axis=None, vmin=6.7, vmax=21.6)  # doctest: +SKIP

.. figure:: ../../_static/style/bg_axNone_vminvmax.png

Setting a ``gmap`` and applying to all columns with another ``cmap``

>>> df.style.background_gradient(axis=0, gmap=df['Temp (c)'], cmap='YlOrRd')
...  # doctest: +SKIP

.. figure:: ../../_static/style/bg_gmap.png

Setting the gradient map for a dataframe (i.e. ``axis=None``), we need to
explicitly state ``subset`` to match the ``gmap`` shape

>>> gmap = np.array([[1,2,3], [2,3,4], [3,4,5]])
>>> df.style.background_gradient(axis=None, gmap=gmap,
...     cmap='YlOrRd', subset=['Temp (c)', 'Rain (mm)', 'Wind (m/s)']
... )  # doctest: +SKIP

.. figure:: ../../_static/style/bg_axNone_gmap.png
File:      /opt/venv/lib/python3.10/site-packages/pandas/io/formats/style.py
Type:      method

In [16]:
r.style.background_gradient(cmap="Greens")

## Customize heatmatrix

### Format numbers

In [17]:
(r
 .div(1000)
 .style
    .format(precision=2)
    .background_gradient(cmap="Greens")
)

### Axis

In [29]:
(r
 .div(1000)
 .style
    .format(precision=2)
    .background_gradient(cmap="Greens", axis=None) # axis = 0 for columns, axis = 1 for rows.
)

## Rankings

### Calculate margins

In [50]:
c_num = "energy"
c_cat_idx = "technology"
c_cat_col = "month"

margins_name = "AVG"

r = df.pivot_table(
    values=c_num,
    index=c_cat_idx,
    columns=c_cat_col,
    aggfunc='mean',
    margins = True,
    margins_name = margins_name
)

r

month,1,2,3,4,5,6,7,8,9,10,11,12,AVG
technology,,,,,,,,,,,,,
Coal,256.860215,231.339080,218.561828,137.995833,196.044355,160.919444,242.415323,405.372312,675.858333,782.419355,692.220833,765.732527,397.836749
Hydro,2390.387097,3555.600575,4087.971774,4153.802778,4769.854839,4114.776389,4353.079301,4275.838710,3497.786111,2255.840054,1872.802778,2004.024194,3444.082878
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wind,1555.297043,1890.843391,2666.627688,2700.608333,3581.381720,3376.955556,2436.137097,2623.821237,2112.944444,1827.712366,1843.634722,1667.287634,2357.827755
AVG,3138.347782,2922.728269,2801.117608,2792.628646,3085.341734,3501.494444,4225.868616,4058.272345,3707.622049,3351.705477,2798.009104,2834.939516,3271.129543

### Sort rows to rank table

In [51]:
(r
 .sort_values(by = 12, ascending = False)
 .style
    .format(precision=2)
)

### Heatmatrix

In [52]:
(r
 .div(1000)
 .sort_values(by = 12, ascending = False)
 .style
    .format(precision=2)
    .background_gradient(cmap="RdYlGn", axis=1)
)

## Pivot table for charts

In [54]:
import plotly.express as px

px.box?

Signature:
px.box(
    data_frame=None,
    x=None,
    y=None,
    color=None,
    facet_row=None,
    facet_col=None,
    facet_col_wrap=0,
    facet_row_spacing=None,
    facet_col_spacing=None,
    hover_name=None,
    hover_data=None,
    custom_data=None,
    animation_frame=None,
    animation_group=None,
    category_orders=None,
    labels=None,
    color_discrete_sequence=None,
    color_discrete_map=None,
    orientation=None,
    boxmode=None,
    log_x=False,
    log_y=False,
    range_x=None,
    range_y=None,
    points=None,
    notched=False,
    title=None,
    subtitle=None,
    template=None,
    width=None,
    height=None,
) -> plotly.graph_objs._figure.Figure
Docstring:
    In a box plot, rows of `data_frame` are grouped together into a
    box-and-whisker mark to visualize their distribution.

    Each box spans from quartile 1 (Q1) to quartile 3 (Q3). The second
    quartile (Q2) is marked by a line inside the box. By default, the
    whiskers correspond to the box' edges +/- 1.5 times the interquartile
    range (IQR: Q3-Q1), see "points" for other options.

Parameters
----------
data_frame: DataFrame or array-like or dict
    This argument needs to be passed for column names (and not keyword
    names) to be used. Array-like and dict are transformed internally to a
    pandas DataFrame. Optional: if missing, a DataFrame gets constructed
    under the hood using the other arguments.
x: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    position marks along the x axis in cartesian coordinates. Either `x` or
    `y` can optionally be a list of column references or array_likes,  in
    which case the data will be treated as if it were 'wide' rather than
    'long'.
y: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    position marks along the y axis in cartesian coordinates. Either `x` or
    `y` can optionally be a list of column references or array_likes,  in
    which case the data will be treated as if it were 'wide' rather than
    'long'.
color: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    assign color to marks.
facet_row: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    assign marks to facetted subplots in the vertical direction.
facet_col: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    assign marks to facetted subplots in the horizontal direction.
facet_col_wrap: int
    Maximum number of facet columns. Wraps the column variable at this
    width, so that the column facets span multiple rows. Ignored if 0, and
    forced to 0 if `facet_row` or a `marginal` is set.
facet_row_spacing: float between 0 and 1
    Spacing between facet rows, in paper units. Default is 0.03 or 0.07
    when facet_col_wrap is used.
facet_col_spacing: float between 0 and 1
    Spacing between facet columns, in paper units Default is 0.02.
hover_name: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like appear in bold
    in the hover tooltip.
hover_data: str, or list of str or int, or Series or array-like, or dict
    Either a name or list of names of columns in `data_frame`, or pandas
    Series, or array_like objects or a dict with column names as keys, with
    values True (for default formatting) False (in order to remove this
    column from hover information), or a formatting string, for example
    ':.3f' or '|%a' or list-like data to appear in the hover tooltip or
    tuples with a bool or formatting string as first element, and list-like
    data to appear in hover as second element Values from these columns
    appear as extra data in the hover tooltip.
custom_data: str, or list of str or int, or Series or array-like
    Either name or list of names of columns in `data_frame`, or pandas
    Series, or array_like objects Values from these columns are extra data,
    to be used in widgets or Dash callbacks for example. This data is not
    user-visible but is included in events emitted by the figure (lasso
    selection etc.)
animation_frame: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    assign marks to animation frames.
animation_group: str or int or Series or array-like
    Either a name of a column in `data_frame`, or a pandas Series or
    array_like object. Values from this column or array_like are used to
    provide object-constancy across animation frames: rows with matching
    `animation_group`s will be treated as if they describe the same object
    in each frame.
category_orders: dict with str keys and list of str values (default `{}`)
    By default, in Python 3.6+, the order of categorical values in axes,
    legends and facets depends on the order in which these values are first
    encountered in `data_frame` (and no order is guaranteed by default in
    Python below 3.6). This parameter is used to force a specific ordering
    of values per column. The keys of this dict should correspond to column
    names, and the values should be lists of strings corresponding to the
    specific display order desired.
labels: dict with str keys and str values (default `{}`)
    By default, column names are used in the figure for axis titles, legend
    entries and hovers. This parameter allows this to be overridden. The
    keys of this dict should correspond to column names, and the values
    should correspond to the desired label to be displayed.
color_discrete_sequence: list of str
    Strings should define valid CSS-colors. When `color` is set and the
    values in the corresponding column are not numeric, values in that
    column are assigned colors by cycling through `color_discrete_sequence`
    in the order described in `category_orders`, unless the value of
    `color` is a key in `color_discrete_map`. Various useful color
    sequences are available in the `plotly.express.colors` submodules,
    specifically `plotly.express.colors.qualitative`.
color_discrete_map: dict with str keys and str values (default `{}`)
    String values should define valid CSS-colors Used to override
    `color_discrete_sequence` to assign a specific colors to marks
    corresponding with specific values. Keys in `color_discrete_map` should
    be values in the column denoted by `color`. Alternatively, if the
    values of `color` are valid colors, the string `'identity'` may be
    passed to cause them to be used directly.
orientation: str, one of `'h'` for horizontal or `'v'` for vertical.
    (default `'v'` if `x` and `y` are provided and both continuous or both
    categorical,  otherwise `'v'`(`'h'`) if `x`(`y`) is categorical and
    `y`(`x`) is continuous,  otherwise `'v'`(`'h'`) if only `x`(`y`) is
    provided)
boxmode: str (default `'group'`)
    One of `'group'` or `'overlay'` In `'overlay'` mode, boxes are on drawn
    top of one another. In `'group'` mode, boxes are placed beside each
    other.
log_x: boolean (default `False`)
    If `True`, the x-axis is log-scaled in cartesian coordinates.
log_y: boolean (default `False`)
    If `True`, the y-axis is log-scaled in cartesian coordinates.
range_x: list of two numbers
    If provided, overrides auto-scaling on the x-axis in cartesian
    coordinates.
range_y: list of two numbers
    If provided, overrides auto-scaling on the y-axis in cartesian
    coordinates.
points: str or boolean (default `'outliers'`)
    One of `'outliers'`, `'suspectedoutliers'`, `'all'`, or `False`. If
    `'outliers'`, only the sample points lying outside the whiskers are
    shown. If `'suspectedoutliers'`, all outlier points are shown and those
    less than 4*Q1-3*Q3 or greater than 4*Q3-3*Q1 are highlighted with the
    marker's `'outliercolor'`. If `'outliers'`, only the sample points
    lying outside the whiskers are shown. If `'all'`, all sample points are
    shown. If `False`, no sample points are shown and the whiskers extend
    to the full range of the sample.
notched: boolean (default `False`)
    If `True`, boxes are drawn with notches.
title: str
    The figure title.
subtitle: str
    The figure subtitle.
template: str or dict or plotly.graph_objects.layout.Template instance
    The figure template name (must be a key in plotly.io.templates) or
    definition.
width: int (default `None`)
    The figure width in pixels.
height: int (default `None`)
    The figure height in pixels.

Returns
-------
    plotly.graph_objects.Figure
File:      /opt/venv/lib/python3.10/site-packages/plotly/express/_chart_types.py
Type:      function

In [58]:
#need to convert to long format for plotly
r_melt= r.melt(ignore_index = False).reset_index() # will lose columns if don't ignore index

In [67]:
idx = r.sort_values(by = "AVG", ascending = False).index

In [68]:
px.box(
    data_frame= r_melt,
    x= "value",
    y = "technology",
    color= "technology",
    category_orders={"technology": idx},
)

In [69]:
px.area(
   data_frame= r_melt,
   x= "month",
   y = "value",
   color= "technology",
)

In [70]:
px.bar(
   data_frame= r_melt,
   x= "month",
   y = "value",
   color= "technology",
)